const state={articles:[],read:new Set(JSON.parse(localStorage.getItem("radar-read")||"[]")),saved:new Set(JSON.parse(localStorage.getItem("radar-saved")||"[]"))};
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
function persist(){localStorage.setItem("radar-read",JSON.stringify([...state.read]));localStorage.setItem("radar-saved",JSON.stringify([...state.saved]));}
function fmt(d){if(!d)return"Data não informada";const x=new Date(d);return Number.isNaN(x.getTime())?d:x.toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"});}
function dayLabel(d){if(!d)return"Data não informada";const x=new Date(d);return Number.isNaN(x.getTime())?"Data não informada":x.toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long",year:"numeric"});}
function priority(a){if(a.priority)return a.priority;const t=(a.title+" "+(a.summary||"")).toLowerCase();if(/prazo|obrigat|entra em vigor|vigência|vigencia|recadastr|regulariz|penalidade|deadline/.test(t))return"ACTION REQUIRED";if(/instabil|alteração|alteracao|atualiza|mudança|mudanca|novo sistema|erro|atenção|atencao|suspens/.test(t))return"ATTENTION";if(/stf|tst|câmara|camara|projeto|decisão|decisao|julgamento|congresso/.test(t))return"FOLLOW";return"KNOWLEDGE";}
function isNew(a){const last=localStorage.getItem("radar-last-visit");if(!last)return true;const t=new Date(a.published_at||a.collected_at||0).getTime();return Number.isFinite(t)&&t>new Date(last).getTime();}
function render(){
 const q=$("#search").value.trim().toLowerCase(),cat=$("#category").value,status=$("#status").value;
 let list=state.articles.filter(a=>(cat==="all"||a.category===cat)&&(!q||[a.title,a.summary,a.source,a.category].join(" ").toLowerCase().includes(q)));
 list=list.filter(a=>status==="all"||(status==="read"&&state.read.has(a.id))||(status==="unread"&&!state.read.has(a.id))||(status==="saved"&&state.saved.has(a.id))||(status==="new"&&isNew(a)));
 $("#resultCount").textContent=list.length+" notícia"+(list.length===1?"":"s");$("#totalCount").textContent=state.articles.length;$("#unreadCount").textContent=state.articles.filter(a=>!state.read.has(a.id)).length;$("#newCount").textContent=state.articles.filter(isNew).length;$("#empty").hidden=list.length!==0;
 let lastDay="",html="";
 for(const a of list){const r=state.read.has(a.id),s=state.saved.has(a.id),p=priority(a),pc=p.toLowerCase().replaceAll(" ","-");const dateKey=(a.published_at||a.collected_at||"").slice(0,10);if(dateKey!==lastDay){html+=`<div class="day-label">${esc(dayLabel(a.published_at||a.collected_at))}</div>`;lastDay=dateKey}html+=`<article class="card ${r?"read":""}"><div class="card-side"><span class="tag">${esc(a.category)}</span><span class="priority ${pc}">${esc(p)}</span></div><div class="card-main"><h3>${esc(a.title)}</h3><p class="summary">${esc(a.summary||"Atualização identificada na fonte oficial. Consulte a publicação original.")}</p><div class="meta"><span>${esc(a.source)}</span><span>•</span><span>${esc(fmt(a.published_at||a.collected_at))}</span>${isNew(a)?'<span>•</span><strong style="color:#20804a">NOVA</strong>':""}</div></div><div class="card-actions"><button class="link" data-open="${esc(a.id)}">Ver detalhes</button><a class="link" href="${esc(a.url)}" target="_blank" rel="noopener" data-mark="${esc(a.id)}">Abrir fonte ↗</a><button class="link" data-read="${esc(a.id)}">${r?"Marcar como não lida":"Marcar como lida"}</button><button class="link save ${s?"on":""}" data-save="${esc(a.id)}">${s?"★ Salva":"☆ Salvar"}</button></div></article>`}
 $("#newsList").innerHTML=html;
 document.querySelectorAll("[data-read]").forEach(el=>el.addEventListener("click",()=>{const id=el.dataset.read;state.read.has(id)?state.read.delete(id):state.read.add(id);persist();render()}));
 document.querySelectorAll("[data-save]").forEach(el=>el.addEventListener("click",()=>{const id=el.dataset.save;state.saved.has(id)?state.saved.delete(id):state.saved.add(id);persist();render()}));
 document.querySelectorAll("[data-mark]").forEach(el=>el.addEventListener("click",()=>{state.read.add(el.dataset.mark);persist()}));
 document.querySelectorAll("[data-open]").forEach(el=>el.addEventListener("click",()=>openArticle(el.dataset.open)));
}
function openArticle(id){const a=state.articles.find(x=>x.id===id);if(!a)return;state.read.add(id);persist();$("#modalContent").innerHTML=`<p class="eyebrow">${esc(a.category)} · ${esc(priority(a))}</p><h2>${esc(a.title)}</h2><div class="modal-meta"><span>${esc(a.source)}</span><span>${esc(fmt(a.published_at||a.collected_at))}</span></div><p class="modal-summary">${esc(a.summary||"Esta atualização foi identificada na fonte oficial. Consulte a publicação original para o conteúdo completo.")}</p><p class="modal-summary"><strong>Por que está no radar:</strong> o item foi capturado automaticamente a partir de uma fonte pública selecionada para acompanhamento do RH.</p><a class="source-btn" href="${esc(a.url)}" target="_blank" rel="noopener">Abrir publicação original ↗</a>`;$("#articleModal").hidden=false;render();}
async function load(){try{const r=await fetch("data/articles.json?ts="+Date.now(),{cache:"no-store"});if(!r.ok)throw new Error("HTTP "+r.status);state.articles=await r.json();const collected=state.articles.map(a=>a.collected_at).filter(Boolean).sort().pop();$("#lastUpdated").textContent=collected?"Última coleta registrada "+fmt(collected):"Arquivo carregado";$("#syncStatus").textContent="Monitorando fontes";render()}catch(e){$("#syncStatus").textContent="Arquivo indisponível";$("#newsList").innerHTML='<div class="empty">Não foi possível carregar o arquivo de notícias agora. Tente novamente em alguns segundos.</div>'}}
async function refresh(){const b=$("#refreshBtn");b.disabled=true;b.textContent="Recarregando...";await load();setTimeout(()=>{b.disabled=false;b.textContent="Recarregar"},500)}
$("#search").addEventListener("input",render);$("#category").addEventListener("change",render);$("#status").addEventListener("change",render);$("#refreshBtn").addEventListener("click",refresh);document.querySelectorAll("[data-close-modal]").forEach(el=>el.addEventListener("click",()=>$("#articleModal").hidden=true));document.addEventListener("keydown",e=>{if(e.key==="Escape")$("#articleModal").hidden=true});load();setInterval(load,300000);setTimeout(()=>{localStorage.setItem("radar-last-visit",new Date().toISOString());render()},1200);